package com.xworkz.application.Collection.mla;

import java.util.ArrayList;
import java.util.Collection;
import java.util.stream.Collectors;

public class mlaRunner {

	public static void main(String[] args) {

		mlaDTO mla1 = new mlaDTO("Shahikala Jolle", 40, "Nippani", "BJP", false, "Female");
		mlaDTO mla2 = new mlaDTO("Govind Karajola", 72, "MUDHOL", "BJP", false, "Male");
		mlaDTO mla3 = new mlaDTO("Mahesh Kumathalli", 55, "Athani", "BJP", false, "Male");
		mlaDTO mla4 = new mlaDTO("Srimanth Patil", 45, "Kagawad", "BJP", false, "Male");
		mlaDTO mla5 = new mlaDTO("P.Rajeev", 56, "Kudachi", "BJP", false, "Male");
		mlaDTO mla6 = new mlaDTO("Duryodhan M Aihole", 46, "Rayabag", "BJP", false, "Male");
		mlaDTO mla7 = new mlaDTO("Umesh Katti", 65, "Hukkeri", "BJP", false, "Male");
		mlaDTO mla8 = new mlaDTO("Balachandra Jarakiholi", 63, "Arabhavi", "BJP", false, "Male");
		mlaDTO mla9 = new mlaDTO("Ramesh Jarakiholi", 44, "Gokak", "BJP", false, "Male");
		mlaDTO mla10 = new mlaDTO("Satish Jarakiholi", 45, "Yemakanamaradi", "INC", false, "Male");
		mlaDTO mla11 = new mlaDTO("Anil S Benake ", 46, "Belagavi Uttar", "BJP", false, "Male");
		mlaDTO mla12 = new mlaDTO("Abhay Patil", 46, "Belagavi Dakshina", "BJP", false, "Male");
		mlaDTO mla13 = new mlaDTO("Lakshmi Hebbalkar", 53, "Belagavi Rural", "INC", false, "Female");
		mlaDTO mla14 = new mlaDTO("Anjali Nimbalkar", 56, "Khanapur", "INC", false, "Female");
		mlaDTO mla15 = new mlaDTO("D. M. Basavantaray", 45, "Kittur", "BJP", false, "Male");
		mlaDTO mla16 = new mlaDTO("Mahantesh Kaujlagi", 53, "Bailhongal", "INC", false, "Male");
		mlaDTO mla17 = new mlaDTO("Anand Mamani", 55, "Saundatti Yellamma", "BJP", false, "Male");
		mlaDTO mla18 = new mlaDTO("Mahadevappa S Yadawad", 65, "Ramdurg", "BJP", false, "Male");
		mlaDTO mla19 = new mlaDTO("Ganesh Hukkeri", 45, "Chikkodi-Sadalaga", "INC", false, "Male");
		mlaDTO mla20 = new mlaDTO("Siddu Savadi", 58, "Terdal", "BJP", false, "Male");
		mlaDTO mla21 = new mlaDTO("Anand Nyamagouda", 57, "Jamkhandi", "INC", false, "Male");
		mlaDTO mla22 = new mlaDTO("Murugesh Nirani", 53, "Bilgi", "BJP", false, "Male");
		mlaDTO mla23 = new mlaDTO("Siddaramaiah", 59, "Badami", "INC", false, "Male");
		mlaDTO mla24 = new mlaDTO("Veerabhadrayya Charantimath", 52, "Bagalkot", "BJP", false, "Male");
		mlaDTO mla25 = new mlaDTO("Doddanagowda Patil", 53, "Hungund", "BJP", false, "Male");
		mlaDTO mla26 = new mlaDTO("A. S. Patil", 56, "Muddebihal", "BJP", false, "Male");
		mlaDTO mla27 = new mlaDTO("Somanagouda Pati", 49, "Devar Hippargi", "BJP", false, "Male");
		mlaDTO mla28 = new mlaDTO("Shivanand S Patil", 35, "Basavana Bagevadi", "INC", false, "Male");
		mlaDTO mla29 = new mlaDTO("M. B. Patil", 48, "Babaleshwar", "INC", false, "Male");
		mlaDTO mla30 = new mlaDTO("Basangouda Patil Yatnal", 65, "Bijapur City", "BJP", false, "Male");
		mlaDTO mla31 = new mlaDTO("Devanand Fulasing Chavan", 63, "Nagathan", "JDS", false, "Male");
		mlaDTO mla32 = new mlaDTO("Y. V. Patil", 67, "Indi", "INC", false, "Male");
		mlaDTO mla33 = new mlaDTO("Ramesh B Bhusanur", 56, "Sindagi", "BJP", false, "Male");
		mlaDTO mla34 = new mlaDTO("M. Y. Patil", 65, "Afzalpur", "INC", false, "Male");
		mlaDTO mla35 = new mlaDTO("Ajay Dharam Singh", 56, "Jevargi", "INC", false, "Male");
		mlaDTO mla36 = new mlaDTO("Rajkumar Patil", 37, "Sedam", "BJP", false, "Male");
		mlaDTO mla37 = new mlaDTO("Avinash Jadhav", 48, "Chincholi", "BJP", false, "Male");
		mlaDTO mla38 = new mlaDTO("Basavaraj Mattimud", 42, "Gulbarga Rural", "BJP", false, "Male");
		mlaDTO mla39 = new mlaDTO("Dattatraya C. Patil Revoor", 46, "Gulbarga Dakshina", "BJP", false, "Male");
		mlaDTO mla40 = new mlaDTO("Kaneez Fatima", 41, "Gulbarga Uttar", "INC", false, "Female");
		mlaDTO mla41 = new mlaDTO("Guttedar Subhash Rukmayya", 49, "Aland", "BJP", false, "Male");
		mlaDTO mla42 = new mlaDTO("Priyank M. Kharge", 47, "Chittapur", "INC", false, "Male");
		mlaDTO mla43 = new mlaDTO("Narasimhanayak", 42, "Shorapur", "BJP", false, "Male");
		mlaDTO mla44 = new mlaDTO("Sharanabasappa Gouda Darshanapur", 52, "Shahapur", "INC", false, "Male");
		mlaDTO mla45 = new mlaDTO("Venkatreddy Mudnal", 58, "Yadgir", "BJP", false, "Male");
		mlaDTO mla46 = new mlaDTO("Naganagowda Kandukar", 53, "Gurmitkal", "JDS", false, "Male");
		mlaDTO mla47 = new mlaDTO("Sharanu Salagar", 59, "Basavakalyan", "BJP", false, "Male");
		mlaDTO mla48 = new mlaDTO("Rajshekar Basavaraj Patil", 54, "Homnabad", "INC", false, "Male");
		mlaDTO mla49 = new mlaDTO("Bandeppa Kashempur", 58, "Bidar South", "JDS", false, "Male");
		mlaDTO mla50 = new mlaDTO("Rahim Khan", 53, "Bidar", "INC", false, "Male");
		mlaDTO mla51 = new mlaDTO("Eshwara Bhimanna Khandre", 50, "Bhalki", "INC", false, "Male");
		mlaDTO mla52 = new mlaDTO("Prabhu Chavhan", 58, "Aurad", "BJP", false, "Male");
		mlaDTO mla53 = new mlaDTO("Basanagouda Daddal", 57, "Raichur Rural", "INC", false, "Male");
		mlaDTO mla54 = new mlaDTO("Dr.Shivaraj Patil S", 56, "Raichur", "BJP", false, "Male");
		mlaDTO mla55 = new mlaDTO("Raja Venkatappa Nayak", 65, "Manvi", "JDS", false, "Male");
		mlaDTO mla56 = new mlaDTO("Shivanagouda Naik", 67, "Devadurga", "BJP", false, "Male");
		mlaDTO mla57 = new mlaDTO("D.S.Hoolageri", 45, "Lingsugur", "INC", false, "Male");
		mlaDTO mla58 = new mlaDTO("Venkatrao Nadagouda", 48, "Sindhanur", "JDS", false, "Male");
		mlaDTO mla59 = new mlaDTO("Basanagouda Turvihal", 50, "Maski", "INC", false, "Male");
		mlaDTO mla60 = new mlaDTO("Amaregouda Linganagouda Patil Bayyapur", 52, "Kushtagi", "INC", false, "Male");
		mlaDTO mla61 = new mlaDTO("Basavaraj Dhadesugur", 58, "Kanakagiri", "BJP", false, "Male");
		mlaDTO mla62 = new mlaDTO("Paranna Munavalli", 44, "Gangawati", "BJP", false, "Male");
		mlaDTO mla63 = new mlaDTO("Achar Halappa Basappa", 49, "Yelburga", "BJP", false, "Male");
		mlaDTO mla64 = new mlaDTO("K.Raghavendra Basavaraj Hitnal", 45, "Koppal", "INC", false, "Male");
		mlaDTO mla65 = new mlaDTO("Ramappa Lamani", 42, "Shirahatti", "BJP", false, "Male");
		mlaDTO mla66 = new mlaDTO("H.K.Patil", 48, "Gadag", "INC", false, "Male");
		mlaDTO mla67 = new mlaDTO("Kalakappa Bandi", 49, "Ron", "BJP", false, "Male");
		mlaDTO mla68 = new mlaDTO("C.C.Patil", 40, "Nargund", "BJP", false, "Male");
		mlaDTO mla69 = new mlaDTO("Patil Munenakoppa Shankar", 47, "Navalgund", "BJP", false, "Male");
		mlaDTO mla70 = new mlaDTO("Kusuma Shivalli", 42, "Kundgol", "INC", false, "Female");
		mlaDTO mla71 = new mlaDTO("Amrupayyappa Desai", 43, "Dharwad", "BJP", false, "Male");
		mlaDTO mla72 = new mlaDTO("Abbayya Prasad", 47, "Hubli-Dharwad-East", "INC", false, "Male");
		mlaDTO mla73 = new mlaDTO("Jagadish Shettar", 65, "Hubli-Dharwad-Central", "BJP", false, "Male");
		mlaDTO mla74 = new mlaDTO("Aravind Bellad", 68, "Hubli-Dharwad-West", "BJP", false, "Male");
		mlaDTO mla75 = new mlaDTO("C.M.Nimbannavar", 69, "Kalghatgi", "BJP", false, "Male");
		mlaDTO mla76 = new mlaDTO("R.V.Deshapande", 62, "Haliyal", "INC", false, "Male");
		mlaDTO mla77 = new mlaDTO("Roopali Naik", 63, "Karwar", "BJP", false, "Female");
		mlaDTO mla78 = new mlaDTO("Dinakar Keshav Shetty", 67, "Kumta", "BJP", false, "Male");
		mlaDTO mla79 = new mlaDTO("Sunil Biliya Naik", 62, "Bhatkal", "BJP", false, "Male");
		mlaDTO mla80 = new mlaDTO("Vishweshwar Hegde Kageri", 63, "Sirsi", "BJP", false, "Male");
		mlaDTO mla81 = new mlaDTO("Arbail Shivaram Hebbar", 67, "Yellapur", "BJP", false, "Male");
		mlaDTO mla82 = new mlaDTO("Srinivas Mane", 69, "Hangal", "INC", false, "Male");
		mlaDTO mla83 = new mlaDTO("Basavaraj Bommai", 67, "Shiggaon", "BJP", false, "Male");
		mlaDTO mla84 = new mlaDTO("Neharu Olekar", 36, "Haveri (SC)", "BJP", false, "Male");
		mlaDTO mla85 = new mlaDTO("Ballary Virupakshappa Rudrappa", 48, "Byadgi", "BJP", false, "Male");
		mlaDTO mla86 = new mlaDTO("B.C.Patil", 45, "Hirekerur", "BJP", false, "Male");
		mlaDTO mla87 = new mlaDTO("Arunkumar Guththur", 42, "Ranibennur", "BJP", false, "Male");
		mlaDTO mla88 = new mlaDTO("P.T.Parameshwar Naik", 43, "Hadagalli", "INC", false, "Male");
		mlaDTO mla89 = new mlaDTO("L.B.P. Bheemanaik", 49, "Hagaribommanahalli", "INC", false, "Male");
		mlaDTO mla90 = new mlaDTO("Anand Singh", 47, "Vijayanagara", "BJP", false, "Male");
		mlaDTO mla91 = new mlaDTO("J.N.Ganesh", 52, "Kampli", "INC", false, "Male");
		mlaDTO mla92 = new mlaDTO("M.S.Somalingappa", 53, "Siruguppa", "BJP", false, "Male");
		mlaDTO mla93 = new mlaDTO("B.Nagendra", 59, "Bellary Rural", "INC", false, "Male");
		mlaDTO mla94 = new mlaDTO("G.Somashekara Reddy", 47, "Bellary City", "BJP", false, "Male");
		mlaDTO mla95 = new mlaDTO("E.Tukaram", 48, "Sandur", "INC", false, "Male");
		mlaDTO mla96 = new mlaDTO("N.Y.Gopalakrishna", 43, "Kudligi", "BJP", false, "Male");
		mlaDTO mla97 = new mlaDTO("B.Sreeramulu", 39, "Molakalmuru", "BJP", false, "Male");
		mlaDTO mla98 = new mlaDTO("T.Raghumurthy", 58, "Challakere", "INC", false, "Male");
		mlaDTO mla99 = new mlaDTO("G.H.Thippareddy", 57, "Chitradurga", "BJP", false, "Male");
		mlaDTO mla100 = new mlaDTO("K.Poornima", 53, "Hiriyur", "BJP", false, "Female");
		mlaDTO mla101 = new mlaDTO("Gulhatty D.Shekhar", 54, "Hosadurga", "BJP", false, "Male");
		mlaDTO mla102 = new mlaDTO("M.Chandrappa", 55, "Holalkere", "BJP", false, "Male");
		mlaDTO mla103 = new mlaDTO("S.V.Ramachandra", 59, "Jagalur", "BJP", false, "Male");
		mlaDTO mla104 = new mlaDTO("G.Karunakara Reddy", 68, "Harapanahalli", "BJP", false, "Male");
		mlaDTO mla105 = new mlaDTO("S.Ramappa", 57, "Harihar", "INC", false, "Male");
		mlaDTO mla106 = new mlaDTO("S.A.Ravindranath", 58, "Davanagere North", "BJP", false, "Male");
		mlaDTO mla107 = new mlaDTO("Shamanur Shivashankarappa", 57, "Davanagere South", "INC", false, "Male");
		mlaDTO mla108 = new mlaDTO("N.Linganna", 65, "Mayakonda", "BJP", false, "Male");
		mlaDTO mla109 = new mlaDTO("K.Madal Veerupakshappa", 51, "Channagiri", "BJP", false, "Male");
		mlaDTO mla110 = new mlaDTO("M.P.Renukacharya", 49, "Honnali", "BJP", false, "Male");
		mlaDTO mla111 = new mlaDTO("K.B.Ashok Naik", 65, "Shimoga Rural", "BJP", false, "Male");
		mlaDTO mla112 = new mlaDTO("B.K.Sangameshwara", 48, "Bhadravati", "INC", false, "Male");
		mlaDTO mla113 = new mlaDTO("K.S.Eshwarappa", 44, "Shimoga", "BJP", false, "Male");
		mlaDTO mla114 = new mlaDTO("Araga Jnanendra", 56, "Tirthahalli", "BJP", false, "Male");
		mlaDTO mla115 = new mlaDTO("B.S.Yeddyurappa", 57, "Shikaripura", "BJP", false, "Male");
		mlaDTO mla116 = new mlaDTO("Kumar Bangarappa", 53, "Soraba", "BJP", false, "Male");
		mlaDTO mla117 = new mlaDTO("Hartalu Halappa", 59, "Sagar", "BJP", false, "Male");
		mlaDTO mla118 = new mlaDTO("B.M.Sukumar Shetty", 40, "Baindur", "BJP", false, "Male");
		mlaDTO mla119 = new mlaDTO("Halady Srinivas Shetty", 50, "Kundapura", "BJP", false, "Male");
		mlaDTO mla120 = new mlaDTO("K.Raghupati Bhat", 60, "Udupi", "BJP", false, "Male");
		mlaDTO mla121 = new mlaDTO("Lalaji Mendon", 45, "Kapu", "BJP", false, "Male");
		mlaDTO mla122 = new mlaDTO("V.Sunil Kumar", 55, "Karkal", "BJP", false, "Male");
		mlaDTO mla123 = new mlaDTO("T.D.Rajegowda", 65, "Sringeri", "INC", false, "Male");
		mlaDTO mla124 = new mlaDTO("M.P.Kumaraswamy", 55, "Mudigere", "BJP", false, "Male");
		mlaDTO mla125 = new mlaDTO("C.T.Ravi", 77, "Chikmagalur", "BJP", false, "Male");
		mlaDTO mla126 = new mlaDTO("D.S.Suresh", 65, "Tarikere", "BJP", false, "Male");
		mlaDTO mla127 = new mlaDTO("Belliprakash", 49, "Kadur", "BJP", false, "Male");
		mlaDTO mla128 = new mlaDTO("J.C.Madhuswamy", 48, "Chiknayakanhalli", "BJP", false, "Male");
		mlaDTO mla129 = new mlaDTO("B.C.Nagesh", 53, "Tiptur", "BJP", false, "Male");
		mlaDTO mla130 = new mlaDTO("Jayaram A S", 51, "Turuvekere", "BJP", false, "Male");
		mlaDTO mla131 = new mlaDTO("Dr.H.D.Ranganath", 47, "Kunigal", "INC", false, "Male");
		mlaDTO mla132 = new mlaDTO("G.B.Jyothi Ganesh", 49, "Tumkur City", "BJP", false, "Male");
		mlaDTO mla133 = new mlaDTO("D.C.Gowrishankar", 47, "Tumkur Rural", "JDS", false, "Male");
		mlaDTO mla134 = new mlaDTO("Dr.G.Parameshwara", 43, "Koratagere", "INC", false, "Male");
		mlaDTO mla135 = new mlaDTO("S.R.Srinivas", 42, "Gubbi", "JDS", false, "Male");
		mlaDTO mla136 = new mlaDTO("C.M.Rajesh Gowda", 50, "Sira", "BJP", false, "Male");
		mlaDTO mla137 = new mlaDTO("Venkata Ramanappa", 47, "Pavagada", "INC", false, "Male");
		mlaDTO mla138 = new mlaDTO("M.V.Veerabhadraiah", 43, "Madhugiri", "JDS", false, "Male");
		mlaDTO mla139 = new mlaDTO("N.H.Shivashankara Reddy", 58, "Gauribidanur", "INC", false, "Male");
		mlaDTO mla140 = new mlaDTO("S.N.Subbareddy", 57, "Bagepalli", "INC", false, "Male");
		mlaDTO mla141 = new mlaDTO("K.Sudhakar", 43, "Chikkaballapur", "BJP", false, "Male");
		mlaDTO mla142 = new mlaDTO("V. Muniyappa", 60, "Sidlaghatta", "INC", false, "Male");
		mlaDTO mla143 = new mlaDTO("J.K.Krishnareddy", 67, "Chintamani", "JDS", false, "Male");
		mlaDTO mla144 = new mlaDTO("K.R.Rameshkumar", 68, "Srinivasapur", "INC", false, "Male");
		mlaDTO mla145 = new mlaDTO("H.Nagesh", 55, "Mulbagal", "IND", true, "Male");
		mlaDTO mla146 = new mlaDTO("M. Roopakala", 47, "Kolar Gold Field", "INC", false, "Female");
		mlaDTO mla147 = new mlaDTO("S.N.Narayanaswamy", 64, "Bangarapet", "INC", false, "Male");
		mlaDTO mla148 = new mlaDTO("K.Srinivasa Gowda", 58, "Kolar", "JDS", false, "Male");
		mlaDTO mla149 = new mlaDTO("K.Y.Nanjegowda", 65, "Malur", "INC", false, "Male");
		mlaDTO mla150 = new mlaDTO("S.R.Vishwanath", 55, "Yelahanka", "BJP", false, "Male");
		mlaDTO mla151 = new mlaDTO("Byrathi Basavaraj", 48, "K.R.Pura", "BJP", false, "Male");
		mlaDTO mla152 = new mlaDTO("Krishna Byre Gowda", 65, "Byatarayanapura", "INC", false, "Male");
		mlaDTO mla153 = new mlaDTO("S.T.Somashekar", 64, "Yeshwanthpur", "BJP", false, "Male");
		mlaDTO mla154 = new mlaDTO("Munirathna", 62, "Rajarajeshwari Nagar", "BJP", false, "Male");
		mlaDTO mla155 = new mlaDTO("R.Manjunatha", 60, "Dasarahalli", "JDS", false, "Male");
		mlaDTO mla156 = new mlaDTO("K.Gopalaiah", 58, "Mahalakshmi Layout", "BJP", false, "Male");
		mlaDTO mla157 = new mlaDTO("Dr.C.N.Ashwath Narayan", 42, "Malleshwaram", "BJP", false, "Male");
		mlaDTO mla158 = new mlaDTO("Suresha BS", 47, "Hebbal", "INC", false, "Male");
		mlaDTO mla159 = new mlaDTO("Akhanda Srinivas Murthy", 47, "Pulakeshinagar", "INC", false, "Male");
		mlaDTO mla160 = new mlaDTO("K.J.George", 53, "Sarvagnanagar", "INC", false, "Male");
		mlaDTO mla161 = new mlaDTO("S.Raghu", 57, "C.V.Raman Nagar", "BJP", false, "Male");
		mlaDTO mla162 = new mlaDTO("Rizwan Arshad", 48, "Shivajinagar", "INC", false, "Male");
		mlaDTO mla163 = new mlaDTO("N.A.Haris", 53, "Shanti Nagar", "INC", false, "Male");
		mlaDTO mla164 = new mlaDTO("Dinesh Gundu Rao", 65, "Gandhi Nagar", "INC", false, "Male");
		mlaDTO mla165 = new mlaDTO("S.Suresh Kumar", 75, "Rajaji Nagar", "BJP", false, "Male");
		mlaDTO mla166 = new mlaDTO("V.Somanna", 72, "Govindraj Nagar", "BJP", false, "Male");
		mlaDTO mla167 = new mlaDTO("M.Krishnappa", 62, "Vijay Nagar", "INC", false, "Male");
		mlaDTO mla168 = new mlaDTO("Zameer Ahmed Khan", 35, "Chamrajpet", "INC", false, "Male");
		mlaDTO mla169 = new mlaDTO("Uday B.Garudachar", 64, "Chickpet", "BJP", false, "Male");
		mlaDTO mla170 = new mlaDTO("L.A.Ravi Subramanya	", 53, "Basavanagudi", "BJP", false, "Male");
		mlaDTO mla171 = new mlaDTO("R.Ashoka", 58, "Padmanaba Nagar", "BJP", false, "Male");
		mlaDTO mla172 = new mlaDTO("Ramalinga Reddy", 57, "B.T.M. Layout", "INC", false, "Male");
		mlaDTO mla173 = new mlaDTO("Soumya Reddy", 52, "Jayanagar", "INC", false, "Female");
		mlaDTO mla174 = new mlaDTO("Aravind Limbavali", 47, "Mahadevapura", "BJP", false, "Male");
		mlaDTO mla175 = new mlaDTO("M Satish Reddy", 46, "Bommanahalli", "BJP", false, "Male");
		mlaDTO mla176 = new mlaDTO("M.Krishnappa", 59, "Bangalore South", "BJP", false, "Male");
		mlaDTO mla177 = new mlaDTO("B.Shivanna", 52, "Anekal", "INC", false, "Male");
		mlaDTO mla178 = new mlaDTO("Sharath Kumar Bachegowda", 56, "Hoskote", "IND", true, "Male");
		mlaDTO mla179 = new mlaDTO("Nisarga Narayanaswamy L.N", 58, "Devanahalli", "JDS", false, "Male");
		mlaDTO mla180 = new mlaDTO("T.Venkataramanaiah", 48, "Doddaballapur", "INC", false, "Male");
		mlaDTO mla181 = new mlaDTO("Dr.K.Srinavasamurthy", 42, "Nelamangala", "JDS", false, "Male");
		mlaDTO mla182 = new mlaDTO("A.Manjunath", 65, "Magadi", "JDS", false, "Male");
		mlaDTO mla183 = new mlaDTO("Anitha Kumaraswamy", 53, "Ramanagara", "JDS", false, "Female");
		mlaDTO mla184 = new mlaDTO("D.K.Shivakumar", 52, "Kanakapura", "INC", false, "Male");
		mlaDTO mla185 = new mlaDTO("H.D.Kumaraswamy", 56, "Channapatna", "JDS", false, "Male");
		mlaDTO mla186 = new mlaDTO("Dr.K.Annadani", 58, "Malavalli", "JDS", false, "Male");
		mlaDTO mla187 = new mlaDTO("D.C.Thammanna", 54, "Maddur", "JDS", false, "Male");
		mlaDTO mla188 = new mlaDTO("C.S.Puttaraju", 61, "Melukote", "JDS", false, "Male");
		mlaDTO mla189 = new mlaDTO("M.Srinivas", 69, "Mandya", "JDS", false, "Male");
		mlaDTO mla190 = new mlaDTO("Ravindra Srikantaiah", 58, "Shrirangapattana", "JDS", false, "Male");
		mlaDTO mla191 = new mlaDTO("Suresh Gowda", 54, "Nagamangala", "JDS", false, "Male");
		mlaDTO mla192 = new mlaDTO("Narayana Gowda", 48, "Krishnarajpet", "BJP", false, "Male");
		mlaDTO mla193 = new mlaDTO("C.N.Balakrishna", 49, "Shravanabelagola", "JDS", false, "Male");
		mlaDTO mla194 = new mlaDTO("K.M.Shivalingegowda", 42, "Arsikere", "JDS", false, "Male");
		mlaDTO mla195 = new mlaDTO("K.S.Lingesha", 46, "	Belur", "JDS", false, "Male");
		mlaDTO mla196 = new mlaDTO("Preetham J.Gowda", 68, "Hassan", "BJP", false, "Male");
		mlaDTO mla197 = new mlaDTO("H.D.Revanna", 62, "Holenarasipur", "JDS", false, "Male");
		mlaDTO mla198 = new mlaDTO("A.T.Ramaswamy", 50, "Arkalgud", "JDS", false, "Male");
		mlaDTO mla199 = new mlaDTO("H.K.Kumaraswamy", 57, "Sakleshpur", "JDS", false, "Male");
		mlaDTO mla200 = new mlaDTO("Harish Poonja", 52, "Belthangady", "BJP", false, "Male");
		mlaDTO mla201 = new mlaDTO("Umanatha A. Kotian", 58, "Moodabidri", "BJP", false, "Male");
		mlaDTO mla202 = new mlaDTO("Bharath Shetty", 65, "Mangalore City North", "BJP", false, "Male");
		mlaDTO mla203 = new mlaDTO("D.Vedavyas Kamath", 49, "Mangalore City South", "BJP", false, "Male");
		mlaDTO mla204 = new mlaDTO("U.T.Khader", 55, "Mangalore", "INC", false, "Male");
		mlaDTO mla205 = new mlaDTO("Rajesh Naik", 46, "	Bantval", "BJP", false, "Male");
		mlaDTO mla206 = new mlaDTO("Sanjeeva Matandoor", 48, "Puttur", "BJP", false, "Male");
		mlaDTO mla207 = new mlaDTO("Angara S", 50, "Sullia", "BJP", false, "Male");
		mlaDTO mla208 = new mlaDTO("Appachu Ranjan", 61, "Madikeri", "BJP", false, "Male");
		mlaDTO mla209 = new mlaDTO("K.G.Bopaiah", 55, "Virajpet", "BJP", false, "Male");
		mlaDTO mla210 = new mlaDTO("K.Mahadeva", 54, "Periyapatna", "JDS", false, "Male");
		mlaDTO mla211 = new mlaDTO("S.R.Mahesh", 46, "Krishnarajanagara", "JDS", false, "Male");
		mlaDTO mla212 = new mlaDTO("H.P.Manjunath", 38, "Hunsuru", "INC", false, "Male");
		mlaDTO mla213 = new mlaDTO("Anil Kumar C.", 39, "Heggadadevankote", "INC", false, "Male");
		mlaDTO mla214 = new mlaDTO("Harshavardhan B.", 44, "Nanjangud", "BJP", false, "Male");
		mlaDTO mla215 = new mlaDTO("GT Devegowda", 47, "Chamundeshwari", "JDS", false, "Male");
		mlaDTO mla216 = new mlaDTO("S.A.Ramadas", 43, "Krishnaraja", "BJP", false, "Male");
		mlaDTO mla217 = new mlaDTO("L.Nagendra", 55, "Chamaraja", "BJP", false, "Male");
		mlaDTO mla218 = new mlaDTO("Tanveer Sait", 58, "Narasimharaja", "INC", false, "Male");
		mlaDTO mla219 = new mlaDTO("Yathindra S.", 52, "Varuna", "INC", false, "Male");
		mlaDTO mla220 = new mlaDTO("Ashvin Kumar M.", 59, "T Narasipura", "JDS", false, "Male");
		mlaDTO mla221 = new mlaDTO("R.Narendra", 56, "Hanur", "INC", false, "Male");
		mlaDTO mla222 = new mlaDTO("N.Mahesh", 53, "Kollegal", "BSP", false, "Male");
		mlaDTO mla223 = new mlaDTO("C.Puttarangashetty", 62, "Chamrajanagar", "INC", false, "Male");
		mlaDTO mla224 = new mlaDTO("C.S.Niranjan Kumar", 58, "Gundlupet", "BJP", false, "Male");

		Collection<mlaDTO> mlas = new ArrayList<>();
		mlas.add(mla1);
		mlas.add(mla2);
		mlas.add(mla3);
		mlas.add(mla4);
		mlas.add(mla5);
		mlas.add(mla6);
		mlas.add(mla7);
		mlas.add(mla8);
		mlas.add(mla9);
		mlas.add(mla10);
		mlas.add(mla11);
		mlas.add(mla12);
		mlas.add(mla13);
		mlas.add(mla14);
		mlas.add(mla15);
		mlas.add(mla16);
		mlas.add(mla17);
		mlas.add(mla18);
		mlas.add(mla19);
		mlas.add(mla20);
		mlas.add(mla21);
		mlas.add(mla22);
		mlas.add(mla23);
		mlas.add(mla24);
		mlas.add(mla25);
		mlas.add(mla26);
		mlas.add(mla27);
		mlas.add(mla28);
		mlas.add(mla29);
		mlas.add(mla30);
		mlas.add(mla31);
		mlas.add(mla32);
		mlas.add(mla33);
		mlas.add(mla34);
		mlas.add(mla35);
		mlas.add(mla36);
		mlas.add(mla37);
		mlas.add(mla38);
		mlas.add(mla39);
		mlas.add(mla40);
		mlas.add(mla41);
		mlas.add(mla42);
		mlas.add(mla43);
		mlas.add(mla44);
		mlas.add(mla45);
		mlas.add(mla46);
		mlas.add(mla47);
		mlas.add(mla48);
		mlas.add(mla49);
		mlas.add(mla50);
		mlas.add(mla51);
		mlas.add(mla52);
		mlas.add(mla53);
		mlas.add(mla54);
		mlas.add(mla55);
		mlas.add(mla56);
		mlas.add(mla57);
		mlas.add(mla58);
		mlas.add(mla59);
		mlas.add(mla60);
		mlas.add(mla61);
		mlas.add(mla62);
		mlas.add(mla63);
		mlas.add(mla64);
		mlas.add(mla65);
		mlas.add(mla66);
		mlas.add(mla67);
		mlas.add(mla68);
		mlas.add(mla69);
		mlas.add(mla70);
		mlas.add(mla71);
		mlas.add(mla72);
		mlas.add(mla73);
		mlas.add(mla74);
		mlas.add(mla75);
		mlas.add(mla76);
		mlas.add(mla77);
		mlas.add(mla78);
		mlas.add(mla79);
		mlas.add(mla80);
		mlas.add(mla81);
		mlas.add(mla82);
		mlas.add(mla83);
		mlas.add(mla84);
		mlas.add(mla85);
		mlas.add(mla86);
		mlas.add(mla87);
		mlas.add(mla88);
		mlas.add(mla89);
		mlas.add(mla90);
		mlas.add(mla91);
		mlas.add(mla92);
		mlas.add(mla93);
		mlas.add(mla94);
		mlas.add(mla95);
		mlas.add(mla96);
		mlas.add(mla97);
		mlas.add(mla98);
		mlas.add(mla99);
		mlas.add(mla100);
		mlas.add(mla101);
		mlas.add(mla102);
		mlas.add(mla103);
		mlas.add(mla104);
		mlas.add(mla105);
		mlas.add(mla106);
		mlas.add(mla107);
		mlas.add(mla108);
		mlas.add(mla109);
		mlas.add(mla110);
		mlas.add(mla111);
		mlas.add(mla112);
		mlas.add(mla113);
		mlas.add(mla114);
		mlas.add(mla115);
		mlas.add(mla116);
		mlas.add(mla117);
		mlas.add(mla118);
		mlas.add(mla119);
		mlas.add(mla120);
		mlas.add(mla121);
		mlas.add(mla122);
		mlas.add(mla123);
		mlas.add(mla124);
		mlas.add(mla125);
		mlas.add(mla126);
		mlas.add(mla127);
		mlas.add(mla128);
		mlas.add(mla129);
		mlas.add(mla130);
		mlas.add(mla131);
		mlas.add(mla132);
		mlas.add(mla133);
		mlas.add(mla134);
		mlas.add(mla135);
		mlas.add(mla136);
		mlas.add(mla137);
		mlas.add(mla138);
		mlas.add(mla139);
		mlas.add(mla140);
		mlas.add(mla141);
		mlas.add(mla142);
		mlas.add(mla143);
		mlas.add(mla144);
		mlas.add(mla145);
		mlas.add(mla146);
		mlas.add(mla147);
		mlas.add(mla148);
		mlas.add(mla149);
		mlas.add(mla150);
		mlas.add(mla151);
		mlas.add(mla152);
		mlas.add(mla153);
		mlas.add(mla154);
		mlas.add(mla155);
		mlas.add(mla156);
		mlas.add(mla157);
		mlas.add(mla158);
		mlas.add(mla159);
		mlas.add(mla160);
		mlas.add(mla161);
		mlas.add(mla162);
		mlas.add(mla163);
		mlas.add(mla164);
		mlas.add(mla165);
		mlas.add(mla166);
		mlas.add(mla167);
		mlas.add(mla168);
		mlas.add(mla169);
		mlas.add(mla170);
		mlas.add(mla171);
		mlas.add(mla172);
		mlas.add(mla173);
		mlas.add(mla174);
		mlas.add(mla175);
		mlas.add(mla176);
		mlas.add(mla177);
		mlas.add(mla178);
		mlas.add(mla179);
		mlas.add(mla180);
		mlas.add(mla181);
		mlas.add(mla182);
		mlas.add(mla183);
		mlas.add(mla184);
		mlas.add(mla185);
		mlas.add(mla186);
		mlas.add(mla187);
		mlas.add(mla188);
		mlas.add(mla189);
		mlas.add(mla190);
		mlas.add(mla191);
		mlas.add(mla192);
		mlas.add(mla193);
		mlas.add(mla194);
		mlas.add(mla195);
		mlas.add(mla196);
		mlas.add(mla197);
		mlas.add(mla198);
		mlas.add(mla199);
		mlas.add(mla200);
		mlas.add(mla201);
		mlas.add(mla202);
		mlas.add(mla203);
		mlas.add(mla204);
		mlas.add(mla205);
		mlas.add(mla206);
		mlas.add(mla207);
		mlas.add(mla208);
		mlas.add(mla209);
		mlas.add(mla210);
		mlas.add(mla211);
		mlas.add(mla212);
		mlas.add(mla213);
		mlas.add(mla214);
		mlas.add(mla215);
		mlas.add(mla216);
		mlas.add(mla217);
		mlas.add(mla218);
		mlas.add(mla219);
		mlas.add(mla220);
		mlas.add(mla221);
		mlas.add(mla222);
		mlas.add(mla223);
		mlas.add(mla224);

		System.out.println("Toatal Numbers of MLA's:" + mlas.size());

		System.out.println("---------MLA's Age is greater than 50-------------");

		mlas.stream().filter(e1 -> e1.getAge() > 50).collect(Collectors.toList())
				.forEach(e1 -> System.out.println(e1.getName()));

		System.out.println("---------MLA's Age is lesser than 50---------------");

		mlas.stream().filter(e2 -> e2.getAge() < 50).collect(Collectors.toList())
				.forEach(e2 -> System.out.println(e2.getName()));

		System.out.println("---------All Male MLA's-----------------");

		mlas.stream().filter(e3 -> e3.getGender().contains("Male")).collect(Collectors.toList())
				.forEach(e3 -> System.out.println(e3.getName()));

		System.out.println("---------All Female MLA's-----------------");

		mlas.stream().filter(e4 -> e4.getGender().contains("Female")).collect(Collectors.toList())
				.forEach(e4 -> System.out.println(e4.getName()));

		System.out.println("----------Sorted collection by Party in ascending order-------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> ref1.getParty().compareTo(ref2.getParty())).forEach(e5 -> System.out
						.println(" Party name: " + e5.getParty() + "  " + " MLA's Name: " + e5.getName()));

		System.out.println("----------Sorted collection by Name in ascending order------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> ref1.getName().compareTo(ref2.getName()))
				.forEach(e6 -> System.out.println("MLA's Name:" + e6.getName()));

		System.out.println("---------Sorted collection by Age in descending order--------------");

		mlas.stream().collect(Collectors.toList()).stream()
				.sorted((ref1, ref2) -> Integer.compare(ref2.getAge(), ref1.getAge()))
				.forEach(e7 -> System.out.println("Age: " + e7.getAge() + "  " + " MLA's Name: " + e7.getName()));

		System.out.println("----------------Collect MLA's by each Constituency-------------");
		
		mlas.stream().filter(e-> e.getConstituency().equals("Kudachi")).collect(Collectors.toList()).forEach(e->System.out.println(e.getName()));

		System.out.println("----------------Collect all MLA's By Party-----------------");

		System.out.println("----------------Find Unique Parties-----------------------");

		mlas.stream().map(e10 -> e10.getParty()).collect(Collectors.toSet()).forEach(e10 -> System.out.println(e10));

		System.out.println("----------------Find Independent MLA's----------------------");

		mlas.stream().filter(e11 -> e11.getParty().contains("IND")).collect(Collectors.toList())
				.forEach(e11 -> System.out.println(e11.getName()));

		System.out.println("-------------Find all MLA's Age >50 and Party is BJP----------");

		mlas.stream().filter(e -> e.getAge() > 50 && e.getParty().matches("BJP")).collect(Collectors.toList())
				.forEach(e -> System.out.println("MLA's:" + e.getName() + " " + " Party is:" + e.getParty()));

	}

}
